
checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    excluded_paths:
        - tests/*
        - spec/*
        - unit/*
        
tools:
    external_code_coverage: true
