
checks:
    python:
        code_rating: true
        duplicate_code: true
        variables_redefined_builtin: true
        classes_bad_classmethod_argument: true
        basic_exec_used: true
        basic_eval_used: true
        basic_dangerous_default_value: true
        classes_method_hidden: true
        classes_bad_mcs_method_argument: true
        classes_super_init_not_called: true
        design_abstract_class_little_used: true


filter:
    excluded_paths:
        - tests/*
        - spec/*
        - unit/*
        
tools:
    external_code_coverage: true
