sudo: false

language: python
python:
    - "2.7"

# command to install dependencies
install: 
    - pip install .
    - pip install coveralls
    - pip install scrutinizer-ocular

# command to run tests
script: 
    - python setup.py test
    - coverage run --source=SwiftFormat setup.py test

after_success: 
    - coveralls
    - ocular --data-file ".coverage"
